models:
  gemma:
    provider: openai
    name: ai/gemma3n:latest
    openai_api_base: http://model-runner.docker.internal/engines/v1
  default:
    provider: ollama
    name: PetrosStav/gemma3-tools:4b
    base_url: http://host.docker.internal:11434
    # you can configure the same model using different temperatures
    # temperature: 1.0
  mistral:
    provider: mistralai
    name: mistral-small-latest
  openai:
    provider: openai
    name: gpt-4o
  claude-sonnet:
    provider: anthropic
    name: claude-sonnet-4-6

vectorstores:
  default:
    provider: postgres
    url: postgresql+psycopg://postgres:5432/postgres
    table_name: aia_ollamax
    embedding:
      provider: ollama
      base_url: http://host.docker.internal:11434
      name: nomic-embed-text
      vector_size: 768
